"""Python SDK for the Voltnir external gRPC API (voltnir.api.v1)."""

__version__ = "2.0.0"

from ._orders import new_client_order_id
from .async_client import AsyncVoltnirClient
from .channel import DEFAULT_CHANNEL_OPTIONS, DEFAULT_MAX_MESSAGE_LENGTH
from .client import VoltnirClient
from .enums import (
    ContractEventType,
    ContractState,
    ExeRestriction,
    ExportFormat,
    MarkSource,
    ModifyAction,
    OrderEventType,
    OrdersEventType,
    OrderState,
    OrderType,
    SelfTradePolicy,
    Side,
    TradeEventType,
    ValidityRes,
)
from .errors import (
    Aborted,
    AsyncLoopError,
    CaCertificateError,
    Cancelled,
    ClientClosed,
    DeadlineExceeded,
    FailedPrecondition,
    Internal,
    InvalidArgument,
    NotFound,
    OrderOutcomeUnknown,
    OrderValidationError,
    PermissionDenied,
    ResourceExhausted,
    Unauthenticated,
    Unavailable,
    VoltnirError,
)
from .units import (
    CASH_SCALE,
    PNL_SCALE,
    PRICE_SCALE,
    QUANTITY_SCALE,
    UnitConversionError,
    cents_to_eur,
    cents_to_price,
    eur_to_cents,
    eur_to_q8,
    price_to_cents,
    q8_to_eur,
    quantity_to_sub_mw,
    sub_mw_to_quantity,
)

__all__ = [
    "__version__",
    "AsyncVoltnirClient",
    "VoltnirClient",
    "new_client_order_id",
    # channel tuning
    "DEFAULT_CHANNEL_OPTIONS",
    "DEFAULT_MAX_MESSAGE_LENGTH",
    # units
    "PRICE_SCALE",
    "QUANTITY_SCALE",
    "CASH_SCALE",
    "PNL_SCALE",
    "UnitConversionError",
    "cents_to_price",
    "price_to_cents",
    "quantity_to_sub_mw",
    "sub_mw_to_quantity",
    "cents_to_eur",
    "eur_to_cents",
    "q8_to_eur",
    "eur_to_q8",
    # enums
    "ContractEventType",
    "ContractState",
    "ExeRestriction",
    "ExportFormat",
    "MarkSource",
    "ModifyAction",
    "OrderEventType",
    "OrdersEventType",
    "OrderState",
    "OrderType",
    "SelfTradePolicy",
    "Side",
    "TradeEventType",
    "ValidityRes",
    # errors
    "Aborted",
    "AsyncLoopError",
    "CaCertificateError",
    "Cancelled",
    "ClientClosed",
    "OrderOutcomeUnknown",
    "OrderValidationError",
    "ResourceExhausted",
    "DeadlineExceeded",
    "FailedPrecondition",
    "Internal",
    "InvalidArgument",
    "NotFound",
    "PermissionDenied",
    "Unauthenticated",
    "Unavailable",
    "VoltnirError",
]
